// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test1.Models;

namespace test1.Migrations
{
    [DbContext(typeof(S21120_DbContext))]
    [Migration("20210513085814_Test2Migration")]
    partial class Test2Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("test1.Models.CityDict", b =>
                {
                    b.Property<int>("IdCityDict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCityDict");

                    b.ToTable("CityDict");

                    b.HasData(
                        new
                        {
                            IdCityDict = 1,
                            City = "cityName1"
                        },
                        new
                        {
                            IdCityDict = 2,
                            City = "cityName2"
                        },
                        new
                        {
                            IdCityDict = 3,
                            City = "cityName3"
                        });
                });

            modelBuilder.Entity("test1.Models.Flight", b =>
                {
                    b.Property<int>("IdFlight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCityDict")
                        .HasColumnType("int");

                    b.Property<int>("IdPlane")
                        .HasColumnType("int");

                    b.HasKey("IdFlight");

                    b.HasIndex("IdCityDict");

                    b.HasIndex("IdPlane");

                    b.ToTable("Flight");

                    b.HasData(
                        new
                        {
                            IdFlight = 1,
                            Comments = "comments1",
                            FlightDate = new DateTime(2021, 5, 13, 10, 58, 13, 610, DateTimeKind.Local).AddTicks(4079),
                            IdCityDict = 1,
                            IdPlane = 1
                        },
                        new
                        {
                            IdFlight = 2,
                            Comments = "comments2",
                            FlightDate = new DateTime(2021, 5, 23, 10, 58, 13, 612, DateTimeKind.Local).AddTicks(5817),
                            IdCityDict = 2,
                            IdPlane = 2
                        },
                        new
                        {
                            IdFlight = 3,
                            Comments = "comments3",
                            FlightDate = new DateTime(2021, 6, 2, 10, 58, 13, 612, DateTimeKind.Local).AddTicks(5860),
                            IdCityDict = 3,
                            IdPlane = 3
                        });
                });

            modelBuilder.Entity("test1.Models.FlightPassenger", b =>
                {
                    b.Property<int>("IdFlight")
                        .HasColumnType("int");

                    b.Property<int>("IdPassenger")
                        .HasColumnType("int");

                    b.HasKey("IdFlight", "IdPassenger")
                        .HasName("Flight_Passenger_PK");

                    b.HasIndex("IdPassenger");

                    b.ToTable("FlightPassenger");

                    b.HasData(
                        new
                        {
                            IdFlight = 1,
                            IdPassenger = 1
                        },
                        new
                        {
                            IdFlight = 2,
                            IdPassenger = 2
                        },
                        new
                        {
                            IdFlight = 3,
                            IdPassenger = 3
                        });
                });

            modelBuilder.Entity("test1.Models.Passenger", b =>
                {
                    b.Property<int>("IdPassenger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PassportNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPassenger");

                    b.ToTable("Passenger");

                    b.HasData(
                        new
                        {
                            IdPassenger = 1,
                            FirstName = "firstName1",
                            LastName = "lastName1",
                            PassportNum = "11111111111"
                        },
                        new
                        {
                            IdPassenger = 2,
                            FirstName = "firstName2",
                            LastName = "lastName2",
                            PassportNum = "2222222222222"
                        },
                        new
                        {
                            IdPassenger = 3,
                            FirstName = "firstName3",
                            LastName = "lastName3",
                            PassportNum = "3333333333"
                        });
                });

            modelBuilder.Entity("test1.Models.Plane", b =>
                {
                    b.Property<int>("IdPlane")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPlane");

                    b.ToTable("Plane");

                    b.HasData(
                        new
                        {
                            IdPlane = 1,
                            MaxSeats = 50,
                            Name = "planeName1"
                        },
                        new
                        {
                            IdPlane = 2,
                            MaxSeats = 30,
                            Name = "planeName2"
                        },
                        new
                        {
                            IdPlane = 3,
                            MaxSeats = 60,
                            Name = "planeName3"
                        });
                });

            modelBuilder.Entity("test1.Models.Flight", b =>
                {
                    b.HasOne("test1.Models.CityDict", "IdCityDictNavigation")
                        .WithMany("Flights")
                        .HasForeignKey("IdCityDict")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("test1.Models.Plane", "IdPlaneNavigation")
                        .WithMany("Flights")
                        .HasForeignKey("IdPlane")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCityDictNavigation");

                    b.Navigation("IdPlaneNavigation");
                });

            modelBuilder.Entity("test1.Models.FlightPassenger", b =>
                {
                    b.HasOne("test1.Models.Flight", "IdFlightNavigation")
                        .WithMany("FlightPassengers")
                        .HasForeignKey("IdFlight")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("test1.Models.Passenger", "IdPassengerNavigation")
                        .WithMany("FlightPassengers")
                        .HasForeignKey("IdPassenger")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdFlightNavigation");

                    b.Navigation("IdPassengerNavigation");
                });

            modelBuilder.Entity("test1.Models.CityDict", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("test1.Models.Flight", b =>
                {
                    b.Navigation("FlightPassengers");
                });

            modelBuilder.Entity("test1.Models.Passenger", b =>
                {
                    b.Navigation("FlightPassengers");
                });

            modelBuilder.Entity("test1.Models.Plane", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
